version: "3.7"

services:
  cbbpoll:
    image: cbbpoll-image
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./dbdata:/data

  test:
    build:
      context: .
      dockerfile: test.Dockerfile

  swagger:
    image: swagger-ui
    build: docs/.
    expose:
      - 8080
    ports:
      - 8080:8080

