on:
  push:
    branches: master

name: Deploy to Google App Engine

jobs:
  deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Make private key file
        uses: jdharms/create-file@master
        with:
          file_contents: ${{ secrets.JWT_PRIV_KEY }}
          file_name: 'backend/jwtRS256.key'

      - name: Make public key file
        uses: jdharms/create-file@master
        with:
          file_contents: ${{ secrets.JWT_PUB_KEY }}
          file_name: 'backend/jwtRS256.key'

      - name: Google Cloud Auth
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Google Cloud Deploy
        uses: actions/gcloud/cli@master
        with:
          args: --quiet app deploy backend
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCLOUD_PROJECT }}

  coverage:
    name: Test Coverage Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Unit tests and go vet
        uses: cedrickring/golang-action@1.3.0
        env:
          PROJECT_PATH: "./backend"
          GO111MODULE: "on"
          IMPORT: "r-cbb/cbbpoll"

      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./backend/coverage.out
          flags: unittests
          name: cbbpoll-unittests