on:
  push:
    branches: master
  pull_request:
    branches: master
name: Golang Actions
jobs:
  checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Unit tests and go vet
        uses: cedrickring/golang-action@1.3.0
        env:
          PROJECT_PATH: "./backend"
          GO111MODULE: "on"
          IMPORT: "r-cbb/cbbpoll"
